version: '3'

services:
  postgres-wg:
    image: postgres
    shm_size: '4gb'
    container_name: postgres-wg
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 30001:5432  
    volumes:
      - postgres:/var/lib/postgresql_wg /data
  rabbit_mq-wg:
    container_name: rabbit_mq-wg
    image: rabbitmq:3-management
    ports:
      - 30002:5672
      - 30003:15672

networks:
  default:
    name: wg-network