@url = https://localhost:4001
# @url = http://localhost:30021
@email = tomasz.krasienko@outlook.com
@password = Test123#
@companyId = 1049eec8-567f-433b-9665-4f10748f7c47
@employeeId = 6e277d1d-4c2b-4c28-99fe-3e2dd90f9bcd

###
GET {{url}}/companies/{{companyId}}

###
GET {{url}}/companies?PageSize=2&PageNumber=1

###
GET {{url}}/companies/employees/users/get-available-roles

###
GET {{url}}/companies/{{companyId}}/employees?PageSize=3&PageNumber1

###
POST {{url}}/companies/register-company
Content-Type: application/json

{
  "name": "OwnerCompany",
  "isOwner": true,
  "emailDomain": "outlook.com"
}

###
POST {{url}}/companies/register-company
Content-Type: application/json

{
  "name": "test2Company",
  "isOwner": false,
  "emailDomain": "test2.com",
  "slaTimeSpan":"10:00:00"
}

###
POST {{url}}/companies/{{companyId}}/add-employee
Content-Type: application/json

{
  "email":"testEmployee3@test2.com" 
}

###
POST {{url}}/companies/employees/{{employeeId}}/sign-up
Content-Type: application/json

{
  "firstName": "Tomasz",
  "lastName": "Krasienko",
  "password": "{{password}}"
}

###
POST {{url}}/companies/employees/users/verify-account
Content-Type: application/json

{
  "verificationToken":"2LNy27p8JX0g3Bm41RTZdxqIIKKBQ3sQurJ94mKtKCDTBIB6Tysz6qvxAOs+fXFkfhx0HCPgwnAjuk8Dvavf3A"
}


###
POST {{url}}/companies/employees/users/sign-in
Content-Type: application/json

{
  "email":"test@outlook.com",
  "password":"{{password}}"
}