@url = https://localhost:4001
# @url = http://localhost:30021
@email = tomasz.krasienko@outlook.com
@password = Test123#
@companyId = 78746a16-8ac2-4ad9-9ac8-b069a593b271
@employeeId = 2094202a-7a20-4869-bc27-dd7a03a6f8bd

###
GET {{url}}/companies/{{companyId}}

###
GET {{url}}/users/get-available-roles

###
POST {{url}}/companies/register-company
Content-Type: application/json

{
  "name": "OwnerCompany",
  "isOwner": true,
  "emailDomain": "outlook.com"
}

###
POST {{url}}/companies/{{companyId}}/add-employee
Content-Type: application/json

{
  "email":"test@outlook.com" 
}

###
POST {{url}}/companies/employees/{{employeeId}}/sign-up
Content-Type: application/json

{
  "firstName": "Tomasz",
  "lastName": "Krasienko",
  "password": "{{password}}",
  "role": "User"
}

###
POST {{url}}/companies/employees/users/verify-account
Content-Type: application/json

{
  "verificationToken":"NXPavfl5G5rRZJOlkAqH5xuotisWpXqOonvG4MGrMwRVfVM0yJkzh31MwW8hgi3O5Gf3V7tydq3k8RBB0UA9g"
}


###
POST {{url}}/companies/employees/users/sign-in
Content-Type: application/json

{
  "email":"test@outlook.com",
  "password":"{{password}}"
}